APPLICATION:
  NAME: Kite
  DESCRIPTION: Kite is a golang code structure generator. It ease to use and helfully to boost your productivity. no need to recreating your code structure when creating a new services, or apps
  VERSION: 0.5.0
